# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 143d254ee0919359989861d3b449b7af9f0a78a91f8728936159b59d02a67b649b2672e6a05239b94ac0ffc38a9488bbcce9810d9b1a32b7126a716250e52cb0

test:
  secret_key_base: 6f05fda627644ea675f80aed22a6d62477214177bb4c440956a180f70aca1ee03f660fb089f378fa31d3e1dd3aa78b16e9adb469d765d07f5c7ab370009ca9ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
